// AUTO-GENERATED by scripts/fetch-destination-images.mjs — do not edit by hand.
export type DestinationImageMeta = {
  src: string;
  width: number;
  height: number;
  photographer: string;
  photographerUrl: string;
  pexelsUrl: string;
};

export const destinationImages: Record<string, Record<string, DestinationImageMeta>> = {
  "japan": {
    "shibuya": {
      "src": "/images/destinations/japan/shibuya.jpg",
      "width": 3905,
      "height": 5858,
      "photographer": "Talha Resitoglu",
      "photographerUrl": "https://www.pexels.com/@talharesitoglu",
      "pexelsUrl": "https://www.pexels.com/photo/bustling-shibuya-crossing-at-twilight-33090036/"
    },
    "fushimi": {
      "src": "/images/destinations/japan/fushimi.jpg",
      "width": 7008,
      "height": 4672,
      "photographer": "G N",
      "photographerUrl": "https://www.pexels.com/@g-n-403098",
      "pexelsUrl": "https://www.pexels.com/photo/vibrant-torii-gates-pathway-in-fushimi-inari-kyoto-29537651/"
    },
    "arashiyama": {
      "src": "/images/destinations/japan/arashiyama.jpg",
      "width": 3848,
      "height": 5776,
      "photographer": "Huu Huynh",
      "photographerUrl": "https://www.pexels.com/@imhh",
      "pexelsUrl": "https://www.pexels.com/photo/arashimaya-bamboo-forest-in-kyoto-18008217/"
    },
    "fuji": {
      "src": "/images/destinations/japan/fuji.jpg",
      "width": 5047,
      "height": 3365,
      "photographer": "Andrey Grushnikov",
      "photographerUrl": "https://www.pexels.com/@andrey-grushnikov-223358",
      "pexelsUrl": "https://www.pexels.com/photo/boat-on-lake-yamanaka-with-mount-fuji-above-the-town-on-the-shore-21759296/"
    },
    "osaka-alley": {
      "src": "/images/destinations/japan/osaka-alley.jpg",
      "width": 4070,
      "height": 4070,
      "photographer": "saw sing",
      "photographerUrl": "https://www.pexels.com/@saw-sing-809441970",
      "pexelsUrl": "https://www.pexels.com/photo/cafe-in-alley-at-night-19499448/"
    },
    "hokkaido-onsen": {
      "src": "/images/destinations/japan/hokkaido-onsen.jpg",
      "width": 3072,
      "height": 4096,
      "photographer": "Maxine Xin",
      "photographerUrl": "https://www.pexels.com/@maxine-xin-706172622",
      "pexelsUrl": "https://www.pexels.com/photo/snowy-hokkaido-winter-scene-with-snowplow-36053227/"
    }
  },
  "india": {
    "jaipur-fort": {
      "src": "/images/destinations/india/jaipur-fort.jpg",
      "width": 6000,
      "height": 4000,
      "photographer": "Abhinav Sharma",
      "photographerUrl": "https://www.pexels.com/@abhi31",
      "pexelsUrl": "https://www.pexels.com/photo/amber-fort-in-amer-in-india-19446861/"
    },
    "varanasi-ghats": {
      "src": "/images/destinations/india/varanasi-ghats.jpg",
      "width": 4672,
      "height": 7008,
      "photographer": "Dmitry Voronov",
      "photographerUrl": "https://www.pexels.com/@onthecrow",
      "pexelsUrl": "https://www.pexels.com/photo/spiritual-morning-ritual-on-varanasi-ghat-31072582/"
    },
    "kerala-backwaters": {
      "src": "/images/destinations/india/kerala-backwaters.jpg",
      "width": 5184,
      "height": 2912,
      "photographer": "Suman Boipai",
      "photographerUrl": "https://www.pexels.com/@suman-boipai-143965246",
      "pexelsUrl": "https://www.pexels.com/photo/scenic-kerala-houseboats-among-tropical-palms-32518360/"
    },
    "ladakh-pass": {
      "src": "/images/destinations/india/ladakh-pass.jpg",
      "width": 2976,
      "height": 3869,
      "photographer": "Sayan Samanta",
      "photographerUrl": "https://www.pexels.com/@stillzonwheelz",
      "pexelsUrl": "https://www.pexels.com/photo/cloud-over-barren-valley-in-mountains-26764585/"
    },
    "agra-detail": {
      "src": "/images/destinations/india/agra-detail.jpg",
      "width": 4500,
      "height": 4500,
      "photographer": "Francesco Ungaro",
      "photographerUrl": "https://www.pexels.com/@francesco-ungaro",
      "pexelsUrl": "https://www.pexels.com/photo/taj-mahal-through-an-arch-206066/"
    },
    "spice-market": {
      "src": "/images/destinations/india/spice-market.jpg",
      "width": 4000,
      "height": 6000,
      "photographer": "Anurag Jamwal",
      "photographerUrl": "https://www.pexels.com/@aj4xo",
      "pexelsUrl": "https://www.pexels.com/photo/street-vendor-with-donkey-in-jalandhar-india-28939322/"
    }
  },
  "italy": {
    "rome-forum": {
      "src": "/images/destinations/italy/rome-forum.jpg",
      "width": 5447,
      "height": 3631,
      "photographer": "Ludovic Delot",
      "photographerUrl": "https://www.pexels.com/@delot",
      "pexelsUrl": "https://www.pexels.com/photo/historic-roman-ruins-at-sunset-in-italy-38041926/"
    },
    "florence-duomo": {
      "src": "/images/destinations/italy/florence-duomo.jpg",
      "width": 4640,
      "height": 6960,
      "photographer": "Efrem  Efre",
      "photographerUrl": "https://www.pexels.com/@efrem-efre-2786187",
      "pexelsUrl": "https://www.pexels.com/photo/black-and-white-photo-of-a-cathedral-15003388/"
    },
    "venice-canal": {
      "src": "/images/destinations/italy/venice-canal.jpg",
      "width": 4000,
      "height": 6000,
      "photographer": "Igor Kira",
      "photographerUrl": "https://www.pexels.com/@igor-kira-774878929",
      "pexelsUrl": "https://www.pexels.com/photo/charming-venetian-canal-with-historic-buildings-30918156/"
    },
    "amalfi-coast": {
      "src": "/images/destinations/italy/amalfi-coast.jpg",
      "width": 5184,
      "height": 2916,
      "photographer": "Bogdan Giurca",
      "photographerUrl": "https://www.pexels.com/@bogdan-giurca-1141359795",
      "pexelsUrl": "https://www.pexels.com/photo/picturesque-view-of-positano-on-the-amalfi-coast-36366053/"
    },
    "tuscany-hills": {
      "src": "/images/destinations/italy/tuscany-hills.jpg",
      "width": 7360,
      "height": 4912,
      "photographer": "Piotr Arnoldes",
      "photographerUrl": "https://www.pexels.com/@piotr-arnoldes-7862031",
      "pexelsUrl": "https://www.pexels.com/photo/a-concrete-pathway-between-trees-7111714/"
    },
    "trattoria": {
      "src": "/images/destinations/italy/trattoria.jpg",
      "width": 4912,
      "height": 4912,
      "photographer": "Wolfgang Weiser",
      "photographerUrl": "https://www.pexels.com/@wolfgang-weiser-467045605",
      "pexelsUrl": "https://www.pexels.com/photo/view-of-a-restaurant-in-a-building-in-a-town-in-tuscany-italy-15969758/"
    }
  },
  "iceland": {
    "aurora": {
      "src": "/images/destinations/iceland/aurora.jpg",
      "width": 5568,
      "height": 3321,
      "photographer": "Kamil Gr",
      "photographerUrl": "https://www.pexels.com/@kamil-gr-3609723",
      "pexelsUrl": "https://www.pexels.com/photo/brown-mountains-under-green-sky-5465018/"
    },
    "black-sand": {
      "src": "/images/destinations/iceland/black-sand.jpg",
      "width": 5845,
      "height": 3897,
      "photographer": "Rostyslav Savchyn",
      "photographerUrl": "https://www.pexels.com/@rossxsavchyn",
      "pexelsUrl": "https://www.pexels.com/photo/landscape-with-black-beach-and-cliffs-9897267/"
    },
    "glacier-lagoon": {
      "src": "/images/destinations/iceland/glacier-lagoon.jpg",
      "width": 3000,
      "height": 4000,
      "photographer": "Hub JACQU",
      "photographerUrl": "https://www.pexels.com/@hub-jacqu-750015482",
      "pexelsUrl": "https://www.pexels.com/photo/dramatic-icebergs-in-iceland-s-jokulsarlon-lagoon-29213491/"
    },
    "geyser": {
      "src": "/images/destinations/iceland/geyser.jpg",
      "width": 2667,
      "height": 4000,
      "photographer": "Laura Paredis",
      "photographerUrl": "https://www.pexels.com/@laura-paredis-1047081",
      "pexelsUrl": "https://www.pexels.com/photo/eruption-of-strokkur-geyser-on-iceland-19499969/"
    },
    "waterfall": {
      "src": "/images/destinations/iceland/waterfall.jpg",
      "width": 2992,
      "height": 2992,
      "photographer": "Lyn Ong",
      "photographerUrl": "https://www.pexels.com/@lyn-ong-2836069",
      "pexelsUrl": "https://www.pexels.com/photo/scenic-view-of-waterfalls-in-the-forest-12993588/"
    },
    "westfjords-road": {
      "src": "/images/destinations/iceland/westfjords-road.jpg",
      "width": 3998,
      "height": 2249,
      "photographer": "Artūras Kokorevas",
      "photographerUrl": "https://www.pexels.com/@kokorevas",
      "pexelsUrl": "https://www.pexels.com/photo/scenic-drive-along-iceland-s-westfjords-coastline-28869748/"
    }
  },
  "norway": {
    "geirangerfjord": {
      "src": "/images/destinations/norway/geirangerfjord.jpg",
      "width": 6000,
      "height": 4000,
      "photographer": "Thea Cintia Paixão da Silva",
      "photographerUrl": "https://www.pexels.com/@cintiapaixao",
      "pexelsUrl": "https://www.pexels.com/photo/stunning-view-of-geirangerfjord-norway-38064840/"
    },
    "lofoten": {
      "src": "/images/destinations/norway/lofoten.jpg",
      "width": 3024,
      "height": 4032,
      "photographer": "Jakub Samberger",
      "photographerUrl": "https://www.pexels.com/@jakub-samberger-2079109211",
      "pexelsUrl": "https://www.pexels.com/photo/scenic-fishing-village-in-lofoten-norway-33361905/"
    },
    "bergen-harbor": {
      "src": "/images/destinations/norway/bergen-harbor.jpg",
      "width": 3815,
      "height": 2861,
      "photographer": "Jonathan Borba",
      "photographerUrl": "https://www.pexels.com/@jonathanborba",
      "pexelsUrl": "https://www.pexels.com/photo/aerial-view-of-bryggen-wharf-in-bergen-norway-33647419/"
    },
    "tromso-aurora": {
      "src": "/images/destinations/norway/tromso-aurora.jpg",
      "width": 4640,
      "height": 6960,
      "photographer": "Efrem  Efre",
      "photographerUrl": "https://www.pexels.com/@efrem-efre-2786187",
      "pexelsUrl": "https://www.pexels.com/photo/nighttime-aerial-view-of-tromso-city-lights-31036779/"
    },
    "midnight-sun": {
      "src": "/images/destinations/norway/midnight-sun.jpg",
      "width": 2693,
      "height": 2693,
      "photographer": "Mone Kostner",
      "photographerUrl": "https://www.pexels.com/@mone-kostner-484319678",
      "pexelsUrl": "https://www.pexels.com/photo/kite-surfing-at-sunrise-over-rocky-beach-38688437/"
    },
    "oslo-opera": {
      "src": "/images/destinations/norway/oslo-opera.jpg",
      "width": 6048,
      "height": 4024,
      "photographer": "Meri Verbina",
      "photographerUrl": "https://www.pexels.com/@meri-verbina-450425482",
      "pexelsUrl": "https://www.pexels.com/photo/oslo-opera-house-operahuset-is-home-of-norwegian-national-opera-and-ballet-building-is-situated-at-head-of-oslofjord-20202718/"
    }
  },
  "switzerland": {
    "matterhorn": {
      "src": "/images/destinations/switzerland/matterhorn.jpg",
      "width": 4000,
      "height": 6000,
      "photographer": "Dario Linder",
      "photographerUrl": "https://www.pexels.com/@dario-linder-21432828",
      "pexelsUrl": "https://www.pexels.com/photo/snow-covered-rocky-mountain-peak-6575786/"
    },
    "lauterbrunnen": {
      "src": "/images/destinations/switzerland/lauterbrunnen.jpg",
      "width": 5053,
      "height": 3254,
      "photographer": "Gotta Be Worth It",
      "photographerUrl": "https://www.pexels.com/@myersmc16",
      "pexelsUrl": "https://www.pexels.com/photo/mountainous-terrain-with-town-and-lush-vegetation-5210151/"
    },
    "lucerne-bridge": {
      "src": "/images/destinations/switzerland/lucerne-bridge.jpg",
      "width": 5976,
      "height": 3984,
      "photographer": "Adrien Olichon",
      "photographerUrl": "https://www.pexels.com/@adrien-olichon-1257089",
      "pexelsUrl": "https://www.pexels.com/photo/chapel-bridge-in-luzern-18429620/"
    },
    "interlaken-lake": {
      "src": "/images/destinations/switzerland/interlaken-lake.jpg",
      "width": 3024,
      "height": 4032,
      "photographer": "Nadin",
      "photographerUrl": "https://www.pexels.com/@nadin-599948827",
      "pexelsUrl": "https://www.pexels.com/photo/turquoise-lake-in-summer-17757886/"
    },
    "alpine-village": {
      "src": "/images/destinations/switzerland/alpine-village.jpg",
      "width": 6000,
      "height": 6000,
      "photographer": "Tobi &Chris",
      "photographerUrl": "https://www.pexels.com/@tobiandchris",
      "pexelsUrl": "https://www.pexels.com/photo/scenic-view-of-a-mountain-9276456/"
    },
    "geneva-lake": {
      "src": "/images/destinations/switzerland/geneva-lake.jpg",
      "width": 6000,
      "height": 4000,
      "photographer": "Altin Rrahmani",
      "photographerUrl": "https://www.pexels.com/@altinrrahmani",
      "pexelsUrl": "https://www.pexels.com/photo/yachts-moored-in-marina-at-sunset-26288980/"
    }
  },
  "morocco": {
    "chefchaouen-blue": {
      "src": "/images/destinations/morocco/chefchaouen-blue.jpg",
      "width": 3024,
      "height": 4032,
      "photographer": "Marina Leonova",
      "photographerUrl": "https://www.pexels.com/@marina-zasorina",
      "pexelsUrl": "https://www.pexels.com/photo/blue-and-brown-tiles-on-concrete-stairs-9422948/"
    },
    "marrakech-souk": {
      "src": "/images/destinations/morocco/marrakech-souk.jpg",
      "width": 3979,
      "height": 3979,
      "photographer": "Salaheddine Es-sellak",
      "photographerUrl": "https://www.pexels.com/@salaheddine-es-sellak-2011499912",
      "pexelsUrl": "https://www.pexels.com/photo/sunlit-alley-in-marrakech-souk-29038454/"
    },
    "sahara-dunes": {
      "src": "/images/destinations/morocco/sahara-dunes.jpg",
      "width": 5958,
      "height": 3972,
      "photographer": "Ed Duvico",
      "photographerUrl": "https://www.pexels.com/@ed-duvico-530456",
      "pexelsUrl": "https://www.pexels.com/photo/vast-sand-dunes-in-merzouga-sahara-desert-29107888/"
    },
    "fes-tannery": {
      "src": "/images/destinations/morocco/fes-tannery.jpg",
      "width": 3888,
      "height": 2592,
      "photographer": "Ramon Karolan",
      "photographerUrl": "https://www.pexels.com/@ramonkaphotography",
      "pexelsUrl": "https://www.pexels.com/photo/colorful-traditional-tanneries-in-fes-morocco-38112369/"
    },
    "riad-courtyard": {
      "src": "/images/destinations/morocco/riad-courtyard.jpg",
      "width": 3648,
      "height": 5472,
      "photographer": "Yassine Oukhadjou",
      "photographerUrl": "https://www.pexels.com/@yassine-oukhadjou-2159611546",
      "pexelsUrl": "https://www.pexels.com/photo/traditional-moroccan-riad-courtyard-with-cat-36209546/"
    },
    "essaouira-port": {
      "src": "/images/destinations/morocco/essaouira-port.jpg",
      "width": 5000,
      "height": 3321,
      "photographer": "Piotr Arnoldes",
      "photographerUrl": "https://www.pexels.com/@piotr-arnoldes-7862031",
      "pexelsUrl": "https://www.pexels.com/photo/anonymous-people-standing-on-wooden-dock-before-fishing-in-sea-6313478/"
    }
  },
  "south-africa": {
    "table-mountain": {
      "src": "/images/destinations/south-africa/table-mountain.jpg",
      "width": 9366,
      "height": 6234,
      "photographer": "Adrien Olichon",
      "photographerUrl": "https://www.pexels.com/@adrien-olichon-1257089",
      "pexelsUrl": "https://www.pexels.com/photo/majestic-view-of-table-mountain-from-the-highway-36597753/"
    },
    "kruger-safari": {
      "src": "/images/destinations/south-africa/kruger-safari.jpg",
      "width": 6124,
      "height": 4816,
      "photographer": "Frans van Heerden",
      "photographerUrl": "https://www.pexels.com/@frans-van-heerden-201846",
      "pexelsUrl": "https://www.pexels.com/photo/elephants-on-brown-mountain-631317/"
    },
    "garden-route": {
      "src": "/images/destinations/south-africa/garden-route.jpg",
      "width": 4000,
      "height": 6000,
      "photographer": "Joshua Brits",
      "photographerUrl": "https://www.pexels.com/@shepherdandwonder",
      "pexelsUrl": "https://www.pexels.com/photo/nature-photography-3116411/"
    },
    "winelands": {
      "src": "/images/destinations/south-africa/winelands.jpg",
      "width": 2899,
      "height": 1922,
      "photographer": "Marina Zvada",
      "photographerUrl": "https://www.pexels.com/@marina-zvada-844583049",
      "pexelsUrl": "https://www.pexels.com/photo/franschhoek-vineyard-with-majestic-mountain-view-31099779/"
    },
    "boulders-beach": {
      "src": "/images/destinations/south-africa/boulders-beach.jpg",
      "width": 2846,
      "height": 2846,
      "photographer": "Ross Valencia",
      "photographerUrl": "https://www.pexels.com/@ross-valencia-2151929110",
      "pexelsUrl": "https://www.pexels.com/photo/humboldt-penguins-at-callao-zoo-peru-31934796/"
    },
    "cape-point": {
      "src": "/images/destinations/south-africa/cape-point.jpg",
      "width": 2832,
      "height": 4240,
      "photographer": "Zhang Thomas",
      "photographerUrl": "https://www.pexels.com/@zhang-thomas-710712620",
      "pexelsUrl": "https://www.pexels.com/photo/dramatic-cliffs-and-ocean-waves-in-south-africa-34168792/"
    }
  },
  "canada": {
    "moraine-lake": {
      "src": "/images/destinations/canada/moraine-lake.jpg",
      "width": 7952,
      "height": 5984,
      "photographer": "Roman Lukyanenko",
      "photographerUrl": "https://www.pexels.com/@roman-lukyanenko-1876017595",
      "pexelsUrl": "https://www.pexels.com/photo/scenic-view-of-moraine-lake-in-canadian-rockies-33730307/"
    },
    "vancouver-skyline": {
      "src": "/images/destinations/canada/vancouver-skyline.jpg",
      "width": 6016,
      "height": 4016,
      "photographer": "Brennan McDonald",
      "photographerUrl": "https://www.pexels.com/@brennanm",
      "pexelsUrl": "https://www.pexels.com/photo/city-at-waterfront-11431965/"
    },
    "quebec-old-town": {
      "src": "/images/destinations/canada/quebec-old-town.jpg",
      "width": 4000,
      "height": 6000,
      "photographer": "Abdel Achkouk",
      "photographerUrl": "https://www.pexels.com/@abdel-achkouk-2861018",
      "pexelsUrl": "https://www.pexels.com/photo/charming-street-scene-in-old-quebec-city-34953802/"
    },
    "jasper-wildlife": {
      "src": "/images/destinations/canada/jasper-wildlife.jpg",
      "width": 5472,
      "height": 3648,
      "photographer": "Aaron Brewer",
      "photographerUrl": "https://www.pexels.com/@aabrewerphoto",
      "pexelsUrl": "https://www.pexels.com/photo/close-up-photo-of-an-elk-13046131/"
    },
    "canoe-lake": {
      "src": "/images/destinations/canada/canoe-lake.jpg",
      "width": 2382,
      "height": 2382,
      "photographer": "Rhiannon Stone",
      "photographerUrl": "https://www.pexels.com/@rhiannonstone",
      "pexelsUrl": "https://www.pexels.com/photo/silhouette-of-man-inside-of-boat-sailing-on-body-of-water-during-sunset-572740/"
    },
    "toronto-skyline": {
      "src": "/images/destinations/canada/toronto-skyline.jpg",
      "width": 3024,
      "height": 4032,
      "photographer": "Nischal Pradhan",
      "photographerUrl": "https://www.pexels.com/@artorias",
      "pexelsUrl": "https://www.pexels.com/photo/toronto-skyline-featuring-the-iconic-cn-tower-at-dusk-38678315/"
    }
  },
  "brazil": {
    "rio-sugarloaf": {
      "src": "/images/destinations/brazil/rio-sugarloaf.jpg",
      "width": 4608,
      "height": 3456,
      "photographer": "Perro Cacahuate",
      "photographerUrl": "https://www.pexels.com/@donadie",
      "pexelsUrl": "https://www.pexels.com/photo/aerial-view-of-rio-de-janeiro-with-sugarloaf-mountain-34416010/"
    },
    "amazon-canopy": {
      "src": "/images/destinations/brazil/amazon-canopy.jpg",
      "width": 2268,
      "height": 4032,
      "photographer": "Leonardo de Jesus Couto",
      "photographerUrl": "https://www.pexels.com/@leonardo-de-jesus-couto-2148720799",
      "pexelsUrl": "https://www.pexels.com/photo/aerial-view-of-waterfall-in-amazon-rainforest-30299891/"
    },
    "iguazu-falls": {
      "src": "/images/destinations/brazil/iguazu-falls.jpg",
      "width": 3000,
      "height": 2003,
      "photographer": "Rodolfo Clix",
      "photographerUrl": "https://www.pexels.com/@rodolfoclix",
      "pexelsUrl": "https://www.pexels.com/photo/iguazu-falls-1203565/"
    },
    "salvador-street": {
      "src": "/images/destinations/brazil/salvador-street.jpg",
      "width": 2333,
      "height": 3500,
      "photographer": "Marcelo Gonzalez",
      "photographerUrl": "https://www.pexels.com/@marcelo-gonzalez-1141370437",
      "pexelsUrl": "https://www.pexels.com/photo/colorful-historic-street-in-bahia-brazil-31792604/"
    },
    "noronha-beach": {
      "src": "/images/destinations/brazil/noronha-beach.jpg",
      "width": 4896,
      "height": 3672,
      "photographer": "Evandro Kluge",
      "photographerUrl": "https://www.pexels.com/@evandro-kluge-201796092",
      "pexelsUrl": "https://www.pexels.com/photo/blue-seascape-and-rocky-coast-12271415/"
    },
    "carnival": {
      "src": "/images/destinations/brazil/carnival.jpg",
      "width": 2448,
      "height": 2448,
      "photographer": "Fernando Eduardo",
      "photographerUrl": "https://www.pexels.com/@fernando-eduardo-95846343",
      "pexelsUrl": "https://www.pexels.com/photo/boys-dancing-with-ribbons-at-city-festival-9250623/"
    }
  },
  "australia": {
    "sydney-harbour": {
      "src": "/images/destinations/australia/sydney-harbour.jpg",
      "width": 7008,
      "height": 4672,
      "photographer": "Donovan Kelly",
      "photographerUrl": "https://www.pexels.com/@donovan-kelly-110228397",
      "pexelsUrl": "https://www.pexels.com/photo/sydney-harbour-bridge-and-sydney-opera-house-26834716/"
    },
    "great-barrier-reef": {
      "src": "/images/destinations/australia/great-barrier-reef.jpg",
      "width": 4000,
      "height": 2256,
      "photographer": "Philippe WEICKMANN",
      "photographerUrl": "https://www.pexels.com/@weickmann",
      "pexelsUrl": "https://www.pexels.com/photo/vibrant-underwater-coral-reef-with-diverse-marine-life-36295207/"
    },
    "uluru": {
      "src": "/images/destinations/australia/uluru.jpg",
      "width": 3613,
      "height": 5420,
      "photographer": "Kate Branch",
      "photographerUrl": "https://www.pexels.com/@katebranch",
      "pexelsUrl": "https://www.pexels.com/photo/aerial-view-of-red-sand-road-in-the-desert-10015971/"
    },
    "great-ocean-road": {
      "src": "/images/destinations/australia/great-ocean-road.jpg",
      "width": 4032,
      "height": 3024,
      "photographer": "Derek Hem",
      "photographerUrl": "https://www.pexels.com/@derek-hem-60706053",
      "pexelsUrl": "https://www.pexels.com/photo/landscape-of-a-cliff-and-a-sea-18222035/"
    },
    "tasmania-forest": {
      "src": "/images/destinations/australia/tasmania-forest.jpg",
      "width": 4176,
      "height": 5568,
      "photographer": "Mark Direen",
      "photographerUrl": "https://www.pexels.com/@mark-direen-622749",
      "pexelsUrl": "https://www.pexels.com/photo/lush-ferns-in-tasmania-s-untouched-wilderness-30115043/"
    },
    "outback-sky": {
      "src": "/images/destinations/australia/outback-sky.jpg",
      "width": 5973,
      "height": 5973,
      "photographer": "Евгений Шухман",
      "photographerUrl": "https://www.pexels.com/@zh-ru",
      "pexelsUrl": "https://www.pexels.com/photo/stars-in-the-evening-sky-10157740/"
    }
  },
  "new-zealand": {
    "milford-sound": {
      "src": "/images/destinations/new-zealand/milford-sound.jpg",
      "width": 2200,
      "height": 1466,
      "photographer": "Pixabay",
      "photographerUrl": "https://www.pexels.com/@pixabay",
      "pexelsUrl": "https://www.pexels.com/photo/body-of-water-surrounded-by-mountains-237260/"
    },
    "queenstown-lake": {
      "src": "/images/destinations/new-zealand/queenstown-lake.jpg",
      "width": 5184,
      "height": 3456,
      "photographer": "Ketan Kumawat",
      "photographerUrl": "https://www.pexels.com/@ketan-kumawat-215630",
      "pexelsUrl": "https://www.pexels.com/photo/green-island-in-the-middle-of-the-lake-during-daytime-724963/"
    },
    "rotorua-geothermal": {
      "src": "/images/destinations/new-zealand/rotorua-geothermal.jpg",
      "width": 2848,
      "height": 4288,
      "photographer": "Julia Foroni",
      "photographerUrl": "https://www.pexels.com/@julia-foroni-3072405",
      "pexelsUrl": "https://www.pexels.com/photo/photo-of-body-of-water-4664658/"
    },
    "abel-tasman": {
      "src": "/images/destinations/new-zealand/abel-tasman.jpg",
      "width": 7008,
      "height": 4672,
      "photographer": "Donovan Kelly",
      "photographerUrl": "https://www.pexels.com/@donovan-kelly-110228397",
      "pexelsUrl": "https://www.pexels.com/photo/sandy-beach-with-a-forest-in-the-background-18915650/"
    },
    "fern-forest": {
      "src": "/images/destinations/new-zealand/fern-forest.jpg",
      "width": 2240,
      "height": 3968,
      "photographer": "Duane Mendes",
      "photographerUrl": "https://www.pexels.com/@duane-mendes-43719258",
      "pexelsUrl": "https://www.pexels.com/photo/person-holding-green-fern-leaf-8763778/"
    },
    "auckland-harbour": {
      "src": "/images/destinations/new-zealand/auckland-harbour.jpg",
      "width": 2992,
      "height": 2992,
      "photographer": "meo",
      "photographerUrl": "https://www.pexels.com/@xespri",
      "pexelsUrl": "https://www.pexels.com/photo/rock-formations-in-a-body-of-water-8021745/"
    }
  }
};
